### ISSUE TITLE
Nodetypes page has no padding in the panel.

### ISSUE THREAD

**Issue by jcoyne** [fcrepo/fcrepo#628]
Seems to be due to

``` css
#metadata .panel-body { text-indent: -35px }
```

![screen shot 2014-11-10 at 2 20 38 pm](https://cloud.githubusercontent.com/assets/92044/4982992/1eaa319a-6917-11e4-9842-7b729cb0c3df.png)
